/**
 * DO NOT EDIT THIS FILE
 */

DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS balance_transactions;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id          int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name        varchar(10) NOT NULL,
  email       varchar(255) NOT NULL,
  phone       varchar(20) NOT NULL,
  birthday    date NOT NULL,
  status      enum('ENABLED', 'DISABLED') NOT NULL,
  created_at  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  datetime
);

CREATE TABLE accounts (
  id                    bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id               int NOT NULL,
  number                varchar(15) NOT NULL,
  amount                bigint NOT NULL,
  status                enum('ENABLED', 'DISABLED') NOT NULL,
  transfer_limit        int NOT NULL,
  daily_transfer_limit  int NOT NULL,
  created_at            datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            datetime,
  UNIQUE KEY unq_accounts_on_number (number),
  KEY idx_accounts_on_user_id       (user_id)
);

CREATE TABLE balance_transactions (
  id                    bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id               int NOT NULL,
  account_id            bigint NOT NULL,
  type                  enum('WITHDRAW', 'DEPOSIT') NOT NULL,
  amount                bigint NOT NULL,
  before_balance_amount bigint NOT NULL,
  note                  varchar(10) NOT NULL,
  created_at            datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_balance_transactions_on_account_id_and_created_at_and_type (account_id, created_at DESC, type),
  KEY idx_balance_transactions_on_user_id_and_created_at (user_id, created_at DESC)
);

CREATE TABLE transfers (
  id          bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id     int NOT NULL,
  withdraw_id bigint NOT NULL,
  deposit_id  bigint NOT NULL,
  amount      bigint NOT NULL,
  created_at  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_transfers_on_user_id      (user_id),
  KEY idx_transfers_on_withdraw_id  (withdraw_id),
  KEY idx_transfers_on_deposit_id   (deposit_id)
);
